### ISSUE TITLE
cleanup docker containers after graceful termination

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-act-runner#12]
When terminating the runner by pressing `Ctrl+C` (SIGINT), it prints the following in console:
```
CTRL+C received, stopping accepting new jobs
Canceled stopping
```
So, it seems it terminates gracefully, but it leaves docker container running after itself:
```
github@xu4r1:~/gha-act-runner$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED         STATUS         PORTS     NAMES
fd2a6f7dd779   arm32v7/debian:buster   "/usr/bin/tail -f /d…"   9 minutes ago   Up 9 minutes             act-ci
```

I think it should stop and remove all the docker containers it spawns during a runtime.

**Comment by igagis** [comment]
still happens with latest snapshot:
```console
^CCTRL+C received, stopping accepting new jobs
Canceled stopping
github@xu4r1:~/github-act-runner$ ls
agent.json  auth.json  cred.pkcs1  github-actions-act-runner-linux-arm
github@xu4r1:~/github-act-runner$ docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS         PORTS     NAMES
f43912b86532   igagis/raspbian:buster   "/usr/bin/tail -f /d…"   6 minutes ago   Up 6 minutes             act-ci
```

**Comment by ChristopherHX** [comment]
I have the feeling, act ignores the config to always remove the container after job exit. (added in the first snaphot of today)
In one issue of act I read the container is kept for debugging purposes.
In any case the container should be removed if you start a job with the same name as the last one. (This has caused container id collisions in act for me)

My github actions wrapper don't know the containerid, act have to be patched.
