### ISSUE TITLE
BrokerMigration message received is rolling out that might cause a downtime until implementation

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/github-act-runner#186]
To reliable implement this, I need access to the rollout of the service update.

Found in this behavior change issue: <https://github.com/actions/runner/issues/3366#issuecomment-2197183513>

**Comment by igagis** [comment]
Starting from yesterday evening, my self-hosted runners do not pick up the jobs anymore, e.g. see https://github.com/cppfw/opros/actions/runs/9785008298

Could this be related to this breaking change?

**Comment by igagis** [comment]
For one of my runners, these are the only logs I have for today:
```
Jul 04 09:07:12 stahl runner[2790276]: Failed to get message, waiting 10 sec before retry: http failure: Http GET Request finished 503 https://pipelines.actions.githubusercontent.com/eMc1GyGdYp1Pn3AIiLBt1AQy39VBhA0ak6WnGv2vWqR163Rx43/_apis/distributedtask/pools/1/messages?api-version=5.1-preview&sessionId=542f6715-7fe1-4f62-90b9-e0b3aff904d1
Jul 04 09:07:12 stahl runner[2790276]: Headers:
Jul 04 09:07:12 stahl runner[2790276]: Cache-Control: no-store
Jul 04 09:07:12 stahl runner[2790276]: Content-Length: 231
Jul 04 09:07:12 stahl runner[2790276]: Content-Type: text/html
Jul 04 09:07:12 stahl runner[2790276]: Date: Thu, 04 Jul 2024 09:07:12 GMT
Jul 04 09:07:12 stahl runner[2790276]: X-Msedge-Ref: Ref A: C7C25762D71C45169960299F1093BFA5 Ref B: STOEDGE1707 Ref C: 2024-07-04T09:07:12Z
Jul 04 09:07:12 stahl runner[2790276]: Body: `{ "message": "GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.", "ref": "Ref A: C7C25762D71C45169960299F1093BFA5 Ref B: STOEDGE1707 Ref C: 2024-07-04T09:07:12Z" }`
```

**Comment by igagis** [comment]
I restarted the runner service, but it didn't help

**Comment by igagis** [comment]
Maybe the breaking change is not involved here and the problem is something else... I'll try to observe more.

**Comment by martijnbastiaan** [comment]
@igagis FWIW We're seeing the same thing. We only see ` BrokerMigration message received. Polling Broker for messages...` and the symptoms (runners not picking up any jobs). This is however with [actions/runner](https://github.com/actions/runner). We'll see if we can enable some debugging flags too.

**Comment by igagis** [comment]
My problem is gone now, perhaps it was some temporary outage of something, not related to this breaking change.
