### ISSUE TITLE
Runner ID given by manager script must be rewised

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-act-runner#22]
From discussion here:

https://github.com/ChristopherHX/github-actions-act-runner/pull/21#discussion_r671754417

it turned out that the runner ID used by the manager script is not "deterministic". I.e. naming convention still allows ID collisions. The ID naming convention must be improved.

Current naming convention is as follows.
The ID consists of runner `name` given by user when creating the runner, the `user/repo` name or `organization` name on the `github.com`. In case of `user/repo` the ID is constructed as `name.user.repo`, in case of org it is `name.organization`. In theory, if `organization` contains dot `.`, then the ID can collide with some `user/repo` ID.

The following must be taken into account when designing new ID convention:
- `systemd` service files must reside in the single directory, no subdirectories allowed, so the ID cannot be a directory hierarchy and must be just in a service file name.
- There can be several runners configured on the same machine under the same linux user having the same `name`, but belonging to different github repos, organizations. Thus, the ID must include github `user`and `repo` or `organization` somehow.
- For github enterprise the domain can be different than `github.com`, so it should also be appended to the ID somehow.
- Possibly the `http/https` can also take it's role.

**Comment by igagis** [comment]
I've just thought that maybe the id must be simply the name given by user, without any repos, orgs, etc. If there is a need to host two runners on the same machine but for different repos and give them the same name, then it could be done from different linux users.

**Comment by igagis** [comment]
@ChristopherHX please let me know if you agree with the solution above, I will make the change then.

**Comment by ChristopherHX** [comment]
I agree, with your solution above. There is no need to add the protocol, domain, org, reponame into the service name.

We could use a service id counter and prefix the runner name with `<number>.`, then increment it every time a service is created.

**Comment by igagis** [comment]
> prefix the runner name with <number>.

why prefix? maybe postfix?

**Comment by ChristopherHX** [comment]
postfix should work too
