### ISSUE TITLE
remove runner from github when removing via script

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-act-runner#25]
Currently the `github-act-runner rm ...` script command will remove all local files associated with the runner, but the runner remains on github.

Need to try to remove the runner from github as well.

Latest snapshot of the runner has `remove` command. Why does it require `--token` argument? Can't the token be saved after runner configuration in config files and used later when removing the runner?
It looks not convenient that user has to go to github web ui to figure out the token in order to remove the runner.

**Comment by ChristopherHX** [comment]
> Can't the token be saved after runner configuration

No the configure token expires 1 hour after creation.
I tried to use the normal runner auth token, but got access denied missing management permission.

Otherwise a personal access token is required to retrieve the token, this is not implemented right now and might cause security issues.

**Comment by igagis** [comment]
Ok, then it adds not value to remove the runner from github using CLI, since user has to go to Runners web UI anyway and, thus, can remove the runner from there as well.

**Comment by igagis** [comment]
I think this issue can be closed as I don't see ways to solve this due to token expiration in 1 hour

**Comment by ChristopherHX** [comment]
I added support for a Personal Access Token (pat) , which don't expire, this could be saved by your management script.
On the other hand a Personal Access Token allows far more than registering and removing runners.

**Comment by igagis** [comment]
Well, generating PAT when registering a new runner just for the sake of removing it later from CLI without necessity of removing it via github web UI doesn't seem like a sane use case :)
