### ISSUE TITLE
Runner receivec SIGINT spontaniously

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-act-runner#33]
I'm currently running 2 runners on 2 `odroid xu4` boards, version 0.0.5.

One of the runners works fine so far.

The other one, for some reason receives SIGINT from somewhere. After starting, it may pick up the job, work for couple of minutes and then gets SIGINT:
```console
github@xu4r1:~$ github-act-runner log xu4r1
running as user 'github'
Jul 20 13:43:51 xu4r1 systemd[7135]: Started github-act-runner '/xu4r1'.
Jul 20 13:43:53 xu4r1 runner[7304]: Listening for Jobs
Jul 20 13:43:58 xu4r1 runner[7304]: Running Job 'linux - igagis/raspbian:buster'
Jul 20 13:43:58 xu4r1 runner[7304]: Failed to upload timeline with Status 404
Jul 20 13:44:16 xu4r1 systemd[7135]: Stopping github-act-runner '/xu4r1'...
Jul 20 13:44:16 xu4r1 runner[7304]: CTRL+C received, stopping accepting new jobs
Jul 20 13:44:16 xu4r1 runner[7304]: Canceled stopping
Jul 20 13:44:20 xu4r1 runner[7304]: Finished Job 'linux - igagis/raspbian:buster' with result: Canceled
Jul 20 13:44:20 xu4r1 systemd[7135]: github-act-runner.xu4r1.service: Succeeded.
Jul 20 13:44:20 xu4r1 systemd[7135]: Stopped github-act-runner '/xu4r1'.
```

I will do more observations.

**Comment by igagis** [comment]
For some reason, service is not restarted, though it has `Restart=always`...

**Comment by ChristopherHX** [comment]
This SIGINT comes from systemd:
```
Jul 20 13:44:16 xu4r1 systemd[7135]: Stopping github-act-runner '/xu4r1'...
```
It looks like the service was stopped by a script, then exited with code 0.

**Comment by igagis** [comment]
strange, because I did not stop it via script... I'll try to reboot the board, just in case

**Comment by ChristopherHX** [comment]
Maybe disable your update restarter: filesystem watching might sometimes see phantom changes.

**Comment by igagis** [comment]
it doesn't look like it is due to that, because it restarts the service and I tested that. In my case, the service is just stopped. I observe some strange behavior, after reboot the service is not started automatically. Maybe user systemd services are not started at boot... trying to figure out what's happening.
Also, on one board after reboot the script `log` command gives `insufficient permissions`. Restarting `systemd-journald` fixes that, but after reboot the error is back again. On the other board that does not happen...

**Comment by ChristopherHX** [comment]
> Maybe user systemd services are not started at boot

It seems they are not started at boot by default, but with some changes to the script and service template it should work:
https://unix.stackexchange.com/questions/251211/why-doesnt-my-systemd-user-unit-start-at-boot
Summary:
- We need `default.target`, the one used (`WantedBy=multi-user.target`) only works for systemwide start on boot.
- Then we need to allow these user services to start on boot instead of waiting for the login `loginctl enable-linger <username>`
- disable and enable the service.

My server keeps running since weeks, so I didn't observed this.

**Comment by igagis** [comment]
yes, I've just figured that out. Made a PR.

Though the `insufficient permissions` problem on one of my boards still remains... I'll investigate it further. But this issue can be closed with the PR.

**Comment by igagis** [comment]
@ChristopherHX 
Could you make a new release, so that I could upgrade my runners?

**Comment by ChristopherHX** [comment]
done, will finish soon

**Comment by igagis** [comment]
Hm, let's wait for another N minutes :).
I think if it doesn't assign a runner in ~10 minutes it makes sense to just restart the workflow...
