### ISSUE TITLE
latest versions of the runner doesn't run commands as from terminal

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-act-runner#35]
Some time ago the runner was running step commands as if from terminal, this produced a nice colored output, for example see here:
https://github.com/cppfw/utki/runs/3079205208?check_suite_focus=true#step:9:59

But latest version of the runner doesn't do that anymore:
https://github.com/cppfw/utki/runs/3106285086?check_suite_focus=true#step:9:60
I.e. `test -t 1` doesn't return 0.
Was this changed intentionally?
Are there problems with running commands as from terminal?

**Comment by ChristopherHX** [comment]
I removed Terminal output to stdout of the runner (would fill journald logs) maybe act assumes now it doesn't run in a Terminal.
> Was this changed intentionally?

No

> Are there problems with running commands as from terminal?

The missing utf8 locale of most docker images [might cause output encoding problems](https://github.com/nektos/act/issues/639).

**Comment by igagis** [comment]
> maybe act assumes now it doesn't run in a Terminal

can this be fixed in `act`? Submit bug there?

**Comment by igagis** [comment]
It's not a big issue, and standard github runner doesn't do that as awell, no colors there. But it was looking nice with colors, so if it is possible to get colors back, that would be great!

**Comment by ChristopherHX** [comment]
> so if it is possible to get colors back, that would be great!

It doesn't seem this is related to runner changes:

- If you are using jobcontainer, then it is due to the systemd service. Running it directly from terminal get colors back. It is possible to add a config to act to force docker to allocate a tty.
- Non docker: never had colors.

**Comment by igagis** [comment]
> it is due to the systemd service

ah, so it is because the runner is started not from terminal, since `systemd` starts it...

**Comment by igagis** [comment]
found this question on SO:
https://stackoverflow.com/questions/32910661/pretend-to-be-a-tty-in-bash-for-any-command/32981392

I haven't investigated it further yet, but maybe it could help starting the runner from service with fake terminal...
Will check it in details later.

**Comment by ChristopherHX** [comment]
> add a config to act to force docker to allocate a tty.

I think this is a better approach than work around this.

e.g. Add `--terminal`, `-t` to enable color like docker even on non terminals

**Comment by igagis** [comment]
Ok, if you know how to do it, then it's fine for me!

**Comment by ChristopherHX** [comment]
You can Test https://github.com/ChristopherHX/github-act-runner/actions/runs/1054002479, there is a debs artifact, then you have to add `-t` to the run command it should allocate a tty. A real Terminal shouldn't alter the behavior of this runner (but act has a different usecase), io is redirected.

It seems pty causes compile errors on some platforms, would need some work to compile again for the whole matrix.

**Comment by igagis** [comment]
I'll test it a bit later.

>  then you have to add -t to the run command

So, the service files have to be changed as well to add this `-t`... Is there a need to run the runner without colors? Maybe make colored mode default?

**Comment by igagis** [comment]
tested it with latest build, works out of the box!

**Comment by ChristopherHX** [comment]
Done, I changed the flag (`-t`) to default to true unless bigger issues appear. Released as 0.0.7.
