### ISSUE TITLE
actions/checkout could be later

### ISSUE THREAD

**Issue by jsoref** [ChristopherHX/github-act-runner#36]
https://github.com/ChristopherHX/github-act-runner/blob/25734399ab65ef15d7088eec4ee1c1936dba6470/.github/workflows/build.yml#L98-L101

@actions/checkout has a `clean` flag that you could set to `0` or `false` if you didn't want to run it first:
https://github.com/actions/checkout/blob/25a956c84d5dd820d28caab9f86b8d183aeeff3d/README.md#L88-L90

**Comment by igagis** [comment]
Ok, good to know! But anyway it works as it is now, it doesn't make much difference what to do first, clone or fetch artifacts.

**Comment by ChristopherHX** [comment]
I'm fine with the contributed deb publish job as it is, no need to reorder the steps.
It might be reasonable to build a job matrix (for each debian arch) around this job, to increase workflow speed.
I wonder how much work it is to allow the other uncommon debian archs to build, like powerpc.

**Comment by jsoref** [comment]
I only note this because the comment at the top of the quoted code seems to be complaining that it has to be in a certain location. You could add the parameter and remove the comment and then put the code wherever you like.

**Comment by ChristopherHX** [comment]
It's fine,

> remove the comment

I removed the quoted comment, but I didn't added any parameter to checkout.
