### ISSUE TITLE
<runner-registration-token> should just point to the <runner-registration-token> section 

### ISSUE THREAD

**Issue by jsoref** [ChristopherHX/github-act-runner#38]
I suspect that this:
https://github.com/ChristopherHX/github-act-runner/blob/3d5727ae377029a21127a60531fa663d7c91dd66/README.md#L36

Was written before this:
https://github.com/ChristopherHX/github-act-runner/blob/3d5727ae377029a21127a60531fa663d7c91dd66/README.md#L82-L88

**Comment by ChristopherHX** [comment]
Good suggestion, the readme needs a fair amount of cleanup and deduplication.

**Comment by jsoref** [comment]
Fwiw, I totally missed the `usage` section of the repository readme. I'm not sure how. (Which is why I went rummaging through the workflow file trying to figure out how to use it....)
