### ISSUE TITLE
Node dependency not documented

### ISSUE THREAD

**Issue by davidchisnall** [ChristopherHX/github-act-runner#42]
This is a fantastic project, thank you!  I have successfully managed to use it to run GitHub actions on a self-hosted FreeBSD runner.  My first attempt failed with a message under a pile of JSON output telling me that node was not found in the path.  It would probably help other folks if the readme mentioned that node needed to be installed.

**Comment by ChristopherHX** [comment]
Thank you for testing this runner.
I added a small section about dependencies in the README file, but technically you can still use composite actions without having node at all.

https://github.com/ChristopherHX/github-act-runner/blob/main/README.md#dependencies

**Comment by davidchisnall** [comment]
Thanks!  I hadn't realised that `actions/checkout@v2` was a node action (I guess I could clone the repo from a run command, I just copied and pasted it from somewhere else - I guess most other people will too?).

What is JobContainer in this context?  I have been wrapping the `run --once` invocation in a jail on FreeBSD (with a wrapper script that uses pot to reset the jail to a previous ZFS snapshot state), but if there's an easy way of extending act to do this then that would be preferable.

**Comment by ChristopherHX** [comment]
>  I guess most other people will too?

Well yes I use it too.

JobContainer is used if you use this property https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer.

I think it would be a large extension to support freebsd jails, but might be possible to so.

**Comment by davidchisnall** [comment]
I see.  For OpenBSD, what does this use?  Is it just a Linux VM?

**Comment by ChristopherHX** [comment]
On openbsd the official go docker client compiled successfully, but failed on freebsd and others.

> Is it just a Linux VM?

I think this requires a linux vm for the docker daemon, but not that I tested this myself.

**Comment by igagis** [comment]
@davidchisnall 

> I guess I could clone the repo from a run command

I have created a custom `checkout` action which doesn't use `node`: https://github.com/marketplace/actions/checkout-github-repo
Feel free to use.

**Comment by davidchisnall** [comment]
Thanks.  Node is fine for my case.  I've put together [some scripts](https://github.com/davidchisnall/act-pot) to set this up on FreeBSD systems, adding node as a dependency is fine, I just needed to know to do it.  Now node and bash are explicitly listed in the README.
