### ISSUE TITLE
[Feature request] Blocking timeout or control channel?

### ISSUE THREAD

**Issue by davidchisnall** [ChristopherHX/github-act-runner#43]
I am running `github-act-runner` with `--once` in a jail that is reset to its pristine state after each invocation.  When I upgrade the jail that contains the runner, I'd like to wait until the runner has completed the job it is currently doing and then replace it with the new jail.  I have no mechanism for making the runner exit if (and only if) it is not currently running a job.

It would be great to have either a pipe I could send a message down to tell the runner to exit if it is idle or a timeout so I can make the agent exit after, say, 5 minute if it doesn't receive a job, then pick up the new version in the restart.

**Comment by ChristopherHX** [comment]
I assume you can send SIGINT to the runner in the jail.
What about changing the behavior of CTRL+C (SIGINT) to not cancel the current running job (if any)?
This project is in an early state, so it wouln't break much.
If you are on a Terminal it should be possible to press CTRL+C again to cancel the current running job if required.

This change would be beneficial for the systemd service to not cancel running jobs during update.

**Comment by davidchisnall** [comment]
Yes, I think that would work.  I can easily run `pkill github-act-runner` in the jail, so if that can make the runner exit at the end of the current job, that would be perfect.

**Comment by ChristopherHX** [comment]
This change is now on the default branch for testing. So a normal git clone would pull it.

**Comment by davidchisnall** [comment]
Fantastic, thank you!  I'll test tomorrow.

**Comment by davidchisnall** [comment]
Works perfectly, thank you!  I can now upgrade the jail that the runner is cloned from and prod it to exit and clone from the new one without interrupting any running jobs.
