### ISSUE TITLE
No cleanup if the runner terminates

### ISSUE THREAD

**Issue by davidchisnall** [ChristopherHX/github-act-runner#45]
If the runner exits in the middle of running a job, GitHub doesn't notice and then refuses to schedule more jobs on the same runner until the timeout (6 hours, by default).  I don't know if there's anything in the protocol that lets a runner say 'I've just restarted, the last job that you think I'm doing failed'.

Note: This may be my fault because nothing in the runner's filesystem is persisted between invocations.  If there's something that I need to preserve, let me know (this is not always possible, but I can do it on the graceful shutdown paths).

**Comment by ChristopherHX** [comment]
Today was an incident with the github actions service:
https://www.githubstatus.com/incidents/7p1nnvkgh96y

Do you have any l

**Comment by davidchisnall** [comment]
I don't have any logs other than the console output, but if you tell me what to print from within the jails, I can add it to the things my script logs.  You're right though, this is similar to the behaviour I saw earlier in the day with hosted runners, so it might just be that the incident is still ongoing.

I've been testing this with a job that does 'sleep 120' in the run line and then killing the runner while it's in the middle of running it, so it's easy for me to reproduce.  I'll try again tomorrow and see if it's still happening.

**Comment by ChristopherHX** [comment]
> console output

The console output of the runner (in the jail) is interesting, because it logs all failed http requests to github.

> killing the runner

What should the runner do if you kill it while it is running? Not all unix signal can be handled.
Only sending sigint will shutdown cleanly.
Sigterm should be handled as well.(not implemented)

I thought about added retry logic for the final timeline / finish job event, but this won't handle killing the runner.
Anyway I don't know all the details of this protocol.

**Comment by ChristopherHX** [comment]
I reread your issue...
So we need to store the sessionid, jobid and timelineid. Then I'm able to mark the job as failed and reclaim lost sessions via http calls.

I'm not shure how you are able to read files on session creation and on job received.

**Comment by ChristopherHX** [comment]
If you keep `./jobrun.json`, then the runner will try to fail the stuck job on next start (up to 10 times on failure).
Since https://github.com/ChristopherHX/github-act-runner/commit/2d5aa8738403739f587e8e93ebda9d39769d23f8

**Comment by davidchisnall** [comment]
Thanks.  I'll add a copy-out and copy-in of that file to my scripts.

**Comment by ChristopherHX** [comment]
I think this issue has been solved.
