### ISSUE TITLE
[Feature Request] Multiple registrations in a single runner

### ISSUE THREAD

**Issue by davidchisnall** [ChristopherHX/github-act-runner#48]
I don't know how feasible this would be, but currently GitHub has a single runner for a single project, org, or enterprise.  We have a few situations where we want to be able to provide some runners for a handful of different projects but not for the full org.  If we run one instance of the runner for each one, then in the worst case we can end up with all of them running at once and hit memory-pressure problems.  The behaviour that I'd like to see is:

1. Runner starts
2. Runner connects to a list of different projects in the idle state
3. When one project provides a job, runner disconnects from the others
4. Runner runs job to completion

I'm using the runner with `--once` and managing the loop and jail-reset outside of the runner, but in the normal mode I presume the right thing to do would be go to step 2.

**Comment by ChristopherHX** [comment]
> We have a few situations where we want to be able to provide some runners for a handful of different projects but not for the full org

The runnergroup feature allow to select specfic repositories self-hosted runner (of a group) are exposed to in an org:
![Screenshot_20210820-135548~2](https://user-images.githubusercontent.com/44845461/130229623-601e5905-b6e4-41c8-8e5a-4aa324efdf52.png)
Enterprise orgs can create multiple runnergroups (I can't do that as free consumer)

However your feature can be implemented with some refactoring, this leads to the question.
How to configure such a scenario?
- Call configure multiple times and save the configuration side by side.
- Add a new configure method
- specify multiple urls and one PAT token then configure it foreach instance with the same name and labels

**Comment by davidchisnall** [comment]
It looks as if the runner group feature only lets runners work within a single org?  We'd like to provide a pool that can be used by multiple orgs.

I think we'd like to be able to dynamically add and remove repos from the set that a runner is configured for, so the first option sounds good to me.

**Comment by ChristopherHX** [comment]
> It looks as if the runner group feature only lets runners work within a single org?

I think this exists on enterprise level too, again I cannot test any enterprise feature.

For non enterprise uses like me, is your feature suggestion the only way to do something like this.

As I made a rather big change and refactoring to get this feature working, this needs to be tested carefully on https://github.com/ChristopherHX/github-act-runner/tree/experimental before merging into main.

We need to monitor stability of this change over weeks.

You should now be able
- to call configure multiple times to add a runner configuration (without override)
- to call remove and select the configurations to remove (--force to ignore if github provides an error about removing)
  - use --name to filter by runner name
  - use --url to filter by registration url
  - use a pat with access to all repos to remove them in one shot
- run will now creates for each configuration a connection to github
  - if a jobrequest were received the message loop will be cancelled (possible race condition!)
  - only the message loop for the current jobrequest will still poll github for cancellation messages
  - on job finish, the runner should exit (--once) or reconnect all sessions

**Comment by davidchisnall** [comment]
Fantastic, thank you!  I am adding GitHub CI to a second project that I want to use the same runners for at the moment, so I hope to be able to test this next week.

**Comment by ChristopherHX** [comment]
I have merged this change into the default branch and is going to be available in v0.1.x.
