### ISSUE TITLE
Trouble creating a Daemonized Version on FreeBSD

### ISSUE THREAD

**Issue by hukl** [ChristopherHX/github-act-runner#55]
Hey there! First of many thanks for this tool. We need to have our builds run on FreeBSD.

However when we try to build the runner via `go build` and try to create a service / daemonized version of it, we run into this error. Do you have any suggestions on how to build a self contained executable other than `go build`? We have already tried many different avenues but our Go knowledge is limited and we figured you might be the best source of information. 

Cheers 

```
he worker panicked with message: runtime error: invalid memory address or nil pointer dereference
goroutine 70 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
main.runJob.func1.6(0xc000523580)
        /usr/local/github_runner/main.go:1107 +0x95
panic({0xb17740, 0x10a1420})
        /usr/local/go/src/runtime/panic.go:1052 +0x2fe
github.com/nektos/act/pkg/runner.(*StepContext).setupEnv(0xc00007e6e0, {0xcbf888, 0xc000235650})
        /usr/local/github_runner/act/pkg/runner/step_context.go:182 +0x80
github.com/nektos/act/pkg/runner.(*RunContext).newStepExecutor.func1({0xcbf888, 0xc000235650})
        /usr/local/github_runner/act/pkg/runner/run_context.go:417 +0x2aa
github.com/nektos/act/pkg/common.Executor.Then.func1({0xcbf888, 0xc000235650})
        /usr/local/github_runner/act/pkg/common/executor.go:145 +0x2b8
github.com/nektos/act/pkg/common.Executor.Then.func1({0xcbf888, 0xc000235650})
        /usr/local/github_runner/act/pkg/common/executor.go:133 +0x46
github.com/nektos/act/pkg/common.Executor.Then.func1({0xcbf888, 0xc000235650})
        /usr/local/github_runner/act/pkg/common/executor.go:133 +0x46
github.com/nektos/act/pkg/common.Executor.Then.func1({0xcbf888, 0xc000235650})
        /usr/local/github_runner/act/pkg/common/executor.go:133 +0x46
github.com/nektos/act/pkg/common.Executor.Finally.func1({0xcbf888, 0xc000235650})
        /usr/local/github_runner/act/pkg/common/executor.go:185 +0x93
github.com/nektos/act/pkg/common.Executor.Finally.func1({0xcbf888, 0xc000235650})
        /usr/local/github_runner/act/pkg/common/executor.go:185 +0x93
github.com/nektos/act/pkg/common.Executor.If.func1({0xcbf888, 0xc000235650})
        /usr/local/github_runner/act/pkg/common/executor.go:153 +0x6a
main.runJob.func1(0xc000230304, 0xc00019b4d0, 0xc000532680, 0xc000532670, {0x1e, {0xc0005589f0, 0x17}, {0xc000558a50, 0x18}, {0xc000310000, ...}}, ...)
        /usr/local/github_runner/main.go:1654 +0x441c
created by main.runJob
        /usr/local/github_runner/main.go:937 +0x16c```

**Comment by ChristopherHX** [comment]
Can you provide the workflow which you are trying to run?
It looks like a bug while converting the github job request to act.
Probably something with env variables of the workflow.

**Comment by hukl** [comment]
So we've cloned the repository, as in the Readme, then cd'ed into the dir and configured it, then ran `go build` and it works fine if we then (still in the directory) manually start it with ./github-act-runner run

But if we wrap it in an rc.d script in freebsd we get this error - probably due to some env issues. The rc.d script looks as follows:

```sh
#!/bin/sh

# PROVIDE: ci_runner

. /etc/rc.subr

name="ci_runner"
rcvar="${name}_enable"

pidfile="/var/run/${name}.pid"

export GOPATH=/usr/local/ci_runner

ci_runner_user="deploy"
ci_runner_chdir="/usr/local/ci_runner"
ci_runner_command="/usr/local/bin/go run . run"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f -t ${name} -o /tmp/ci_runner.log ${ci_runner_command}"

load_rc_config "${name}"
: ${ci_runner_enable:=no}

run_rc_command "$1"
```

**Comment by hukl** [comment]
We are using the daemon wrapper (https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=8&format=html) as we are not sure if a built executable would work by itself

**Comment by ChristopherHX** [comment]
I mean the github workflow file which you are trying to run. This isn't an installation error. You found a bug.

**Comment by hukl** [comment]
Hmm but the workflow works fine when we start it manually - either way here it is:

```yaml
name: Build

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'staging'
    tags:
      - 'v*'

env:
  ELIXIR_VERSION: '1.12.3'
  OTP_VERSION: '23.2.1'

jobs:
  build:
    name: Build
    runs-on: [self-hosted, freebsd, amd64]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data

      - name: Build and Deploy
        run: |
          export PATH=/usr/local/elixir/bin:$PATH
          mix local.hex --force && mix local.rebar --force
          mix deps.get
          MIX_ENV=container mix release our_app
          build_name=$(date +%Y%m%d%H%M%S)
          cp _build/container/our_app-*.tar.gz /tmp/$build_name.tgz
          hosts=$(drill SRV _ggrooms.production.svc.soba.lan. | grep "^_ggrooms" | cut -w -f 8)
          printf "$hosts" | xargs -P 0 -I HOST scp -o StrictHostKeyChecking=no /tmp/$build_name.tgz HOST:/tmp/
          printf "$hosts" | xargs -P 0 -I HOST ssh HOST mkdir /usr/local/www/our_app/$build_name
          printf "$hosts" | xargs -P 0 -I HOST ssh HOST tar xvzf /tmp/$build_name.tgz -C /usr/local/www/our_app/$build_name
          printf "$hosts" | xargs -P 0 -I HOST ssh HOST sudo service our_app stop
          printf "$hosts" | xargs -P 0 -I HOST ssh HOST ln -sF /usr/local/www/our_app/$build_name /usr/local/www/our_app/current
          printf "$hosts" | xargs -P 0 -I HOST ssh HOST sudo service our_app start```

**Comment by ChristopherHX** [comment]
Can you please build the runner from branch v0.1.x? Maybe this reveals the real error.
The default branch of this runner, contains some unstable changes which leads to panics on errors.

**Comment by hukl** [comment]
Ok checked out the v0.1.x branch, did a `git submodule update` and then ran `go build`. The runner is starting but the job fails with 

```
Runner Name: freebsd-runner
Runner OSDescription: github-act-runner freebsd/amd64
Runner Version: 0.0.0
Error: mkdir /.cache: permission denied
```

Not sure why it would try to do that in the `/` but looks less threatening ;)

**Comment by ChristopherHX** [comment]
Ah your env variable `HOME` is empty.
Could you set it?

**Comment by hukl** [comment]
Hmm I've tried adding it to the rc.d script but that didn't help. It looks like this and usually setting env vars like this works

```sh
#!/bin/sh

# PROVIDE: ci_runner

. /etc/rc.subr

name="ci_runner"
rcvar="${name}_enable"

pidfile="/var/run/${name}.pid"

export HOME=/usr/local/ci_runner

ci_runner_user="deploy"
ci_runner_chdir="/usr/local/ci_runner"
ci_runner_command="/usr/local/ci_runner/github-act-runner run"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f -t ${name} -o /tmp/ci_runner.log ${ci_runner_command}"

load_rc_config "${name}"
: ${ci_runner_enable:=no}

run_rc_command "$1"
```

**Comment by hukl** [comment]
I will investigate if there are other options to set the home in the rc script / or check how I could pass that along into the daemon perhaps

**Comment by ChristopherHX** [comment]
Weird enough changing `HOME` like you did in https://github.com/ChristopherHX/github-act-runner/issues/55#issuecomment-1031864045 does work for me on a freebsd vm.

However I had to change the permissions of `/usr/local/ci_runner`, I only have the user azureuser and not deploy
`sudo chown -R azureuser:azureuser /usr/local/ci_runner`

```sh
#!/bin/sh

# PROVIDE: ci_runner

. /etc/rc.subr

name="ci_runner"
rcvar="${name}_enable"

pidfile="/usr/local/ci_runner/${name}.pid"

export HOME=/usr/local/ci_runner

ci_runner_user="azureuser"
ci_runner_chdir="/usr/local/ci_runner"
ci_runner_command="/usr/local/ci_runner/github-act-runner run"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f -t ${name} -o /tmp/ci_runner.log ${ci_runner_command}"

load_rc_config "${name}"
: ${ci_runner_enable:=no}

run_rc_command "$1"
```
ran with `sudo /etc/rc.d/act-runner onestart`

Are you shure your changes were applied to the runner daemon?

I have used a freebsd 13.0 vm on azure.

_BTW thanks for your freebsd service file, since I'm don't know freebsd very well._

**Comment by hukl** [comment]
Oh really? with this exact script I've posted? Can you post yours just to be 100% sure? :) And I gladly provide some FreeBSD inside which is my favorite server os :)

**Comment by ChristopherHX** [comment]
> with this exact script I've posted? 

No, but very similar ( yes I posted my script here https://github.com/ChristopherHX/github-act-runner/issues/55#issuecomment-1031894741 )
- how to create the user deploy
- make `/var/run/${name}.pid` writeable for user deploy

**Comment by hukl** [comment]
Ok the only difference then is that i'm running it in a Jail (pre cursor to linux containers) maybe I have to tweak the PATH in there :) Will investigate some more but thanks for the help already

**Comment by hukl** [comment]
oh and it seems the name for the runner is conflicting I'm now getting: 

```
Failed to recreate Session for freebsd-runner ( https://github.com/guessing-game ), waiting 30 sec before retry: request POST https://pipelines.actions.githubusercontent.com/gXidXLifxtZhf06DOaIZ8CZlfFCg670lXZ4NUqdGHJ54jcvieb/_apis/distributedtask/pools/1/sessions failed with status 409, requestBody: `` and responseBody: `{"$id":"1","innerException":null,"message":"The actions runner freebsd-runner already has an active session for owner RUNNER.","typeName":"Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentSessionConflictException, Microsoft.TeamFoundation.DistributedTask.WebApi","typeKey":"TaskAgentSessionConflictException","errorCode":0,"eventId":3000}`
```

so maybe stop yours? weird

**Comment by hukl** [comment]
Now I've changed the workflow file and generated a new commit and that seemed to have fixed it. I guess something conflicting was cached and maybe that is why my changes didn't really have effect?

**Comment by hukl** [comment]
Double checked that - and indeed - if I edit the workflow file to generate a commit it works opposed to changing the rc script, restarting the service and re-running the same job … phew thanks for guiding me through this :D

**Comment by hukl** [comment]
Hey - with delight I noticed the pre-built freebsd binaries for the 0.2 release. I've tested it and it seems to work great! Many thanks! Maybe also a good opportunity to close this issue?
