### ISSUE TITLE
fatal: unsafe repository ('/__w/<dir>/<dir> is owned by someone else)

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-act-runner#56]
I don't know what and where has changed but now I get this error when running a job in `ubuntu:focal` container:

https://github.com/cppfw/prorab/runs/6039741980?check_suite_focus=true#step:5:63

This is my own action, and the error happens on this line:

https://github.com/myci-actions/checkout/blob/master/action.yml#L46

I'm wondering, if `github-act-runner` could explicitly change ownership of the mounted directory to avoid this error?

Note, that running the same job in `debian:bullseye` and other `debian` containers work fine, without errors.

**Comment by ChristopherHX** [comment]
You are hitting
- https://github.blog/2022-04-12-git-security-vulnerability-announced/
- https://github.com/actions/runner/pull/1823
- https://github.com/actions/checkout/issues/760

@igagis Is this also a problem with github-act-runner? Your provided log is from actions/runner, act doesn't use bind mounts into the container.

**Comment by igagis** [comment]
Ah, yes, sorry, my bad, this is a public runner. Sorry for false request.

**Comment by igagis** [comment]
And thanks for info, I was able to fix my `checkout` action :)
