### ISSUE TITLE
Add optional timeout for waiting for jobs in ephemeral mode?

### ISSUE THREAD

**Issue by nwf** [ChristopherHX/github-act-runner#60]
Could we get a way to bound the amount of time spent waiting for a job, at https://github.com/ChristopherHX/github-act-runner/blob/e596b4f663c83ca1e37e0b27555ea8b069fb1f8f/main.go#L879, if we're `--ephemeral`?

In particular, the concerning scenarios are of this form: if someone creates a PR which kicks off a request for ephemeral runners, and then cancels the workflow before the ephemeral runner is actually ready, the runner will subsequently come up and get stuck, here, because no jobs remain in GitHub's queue.

This is tangentially related to #59, in that the runner doesn't know what job it was created for and so doesn't know that the job has already been cancelled.  Moreover, while we do get a cancellation push message (a `workflow_job` message indicating `"completed"` but with a `null` runner), we can't teardown the environment of the runner associated by job ID, because it might have picked up a different job with the same labels in the same repository.  It's all kind of sad. :(

Anyway, if there's existing support for this and I've merely overlooked it, I'm sorry for the noise.

**Comment by ChristopherHX** [comment]
I'm not shure if you need a timeout to do that.

The following feature is not documented and is different compared to actions/runner

Send `sigint` to the runner process, if you only send it once this runner keep any job running and stops as soon as no job is running. 

_Another `sigint` / `sigterm` will cancel any running job, which is not what you want_

**Comment by nwf** [comment]
Oh, fantastic!  Yes, that should work great.  Thanks!

**Comment by nwf-msr** [comment]
Ah, but, minor issue: it looks like ephemeral runners don't clean themselves up if told to stop waiting with a single `SIGINT`, so they linger as registered on github and need to be manually cleaned up.

**Comment by ChristopherHX** [comment]
> ephemeral runners don't clean themselves up

I tried to do it, but it seems like the registred agent haven't enough permission to delete itself from the service. The actions service seem to delete an ephemeral runner only after it received one job, otherwise you either have to delete it with a runner registration/delete / PAT token or wait 30 days then githubs does it for you.

You will see the same behavior for actions/runner.

**Comment by nwf** [comment]
Thanks for investigating!  I will see about adding logic on the management node to de-register the runner if it sees a runner time out while waiting.
